name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Verify POM.xml exists
      run: ls -la Java  # POM.xml байгаа эсэхийг шалгах

    - name: Build with Maven
      working-directory: Java
      run: mvn install -B  

    - name: Run tests with Maven
      working-directory: Java
      run: mvn test || true 
    - name: Upload Surefire Reports
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports
        path: Java/target/surefire-reports

    - name: Run tests with Maven (Debug)
      working-directory: Java
      run: mvn test -e -X  # Enables detailed error logs

